### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by eeskbala** [OLIMEX/ESP32-ADF#1]
We are having issues compiling the current HEAD on the master

esp-idf/components/asio/asio/asio/src/asio.cpp:11:
/home/skb/.espressif/tools/xtensa-esp32-elf/esp32-2019r1-8.2.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/stdlib.h:155:44: error: expected initializer before '__result_use_check'
 void *reallocarray(void *, size_t, size_t) __result_use_check __alloc_size(2)

**Comment by DanKoloff** [comment]
Which of the two examples are you trying to compile? Can you also give us more details about your software setup?
