### ISSUE TITLE
MOD-SD_MMC compatiblity

### ISSUE THREAD

**Issue by timotoots** [OLIMEX/ESP32-ADF#2]
Would you mind explaining or making a demo how to connect your SD Card UEXT reader to ESP32-ADF and play files from the card? The demos of ESP-ADF are not working out of the box.

**Comment by DanKoloff** [comment]
These two should work together just fine.

Navigate to the the IDF component in the ADF framework. Get to the SD card example and read the info: https://github.com/espressif/esp-idf/tree/4aa1058e8a8f7f3fb17d9ac1158227ad161f2996/examples/storage/sd_card

You only need to edit the beginning of the code to the proper pins (refer to the schematic of the board that shows the UEXT for the proper pins in case I made a mistake):

#ifdef USE_SPI_MODE
// Pin mapping when using SPI mode.
// With this mapping, SD card can be used both in SPI and 1-line SD mode.
// Note that a pull-up on CS line is required in SD mode.
#define PIN_NUM_MISO 15
#define PIN_NUM_MOSI 2
#define PIN_NUM_CLK  14
#define PIN_NUM_CS   21
#endif //USE_SPI_MODE

IMPORTANT: This applies only for revision B of the ESP32-ADF board. Future revisions might have it different.
