### ISSUE TITLE
Reading battery voltage

### ISSUE THREAD

**Issue by jwktje** [OLIMEX/ESP32-ADF#8]
Is there a way to read the battery voltage and get a rough estimate of the remaining battery percentage?

I tried looking for a voltage divider for this in the schematic but couldn’t find it.

**Comment by DanKoloff** [comment]
ESP32-ADF has no battery voltage measuring nor battery presence functionality. You can check how this functionality was enabled in ESP32-POE or ESP32-POE-ISO if you wish to implement such. You can find these here (in the top left section named "Power supply"):

https://github.com/OLIMEX/ESP32-POE/blob/master/HARDWARE/ESP32-PoE-hardware-revision-I/ESP32-PoE_Rev_I.pdf

https://github.com/OLIMEX/ESP32-POE-ISO/blob/master/HARDWARE/ESP32-PoE-ISO-Rev.H/ESP32-PoE-ISO_Rev_H.pdf

**Comment by jwktje** [comment]
@DanKoloff I see. It looks like I would need to sacrifice the Mode button as there is no free GPIO for this on the ESP32-ADF. Would you guys consider a revision or alternate version that removes the Mode button in exchange for external battery voltage sensing?
